spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/bdexaventas
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
# swagger-ui custom path
springdoc:
  swagger-ui.path:  /swagger-ui.html
  # /api-docs endpoint custom path
  api-docs.path:  /api-docs
  info:
    version:  1.0
    title:  api-ventas
    description:  Examen Arquitectura Hexagonal
    servers:
      - http://localhost:8080